apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  labels:
    env: test
spec:
  containers:
    - name: c00
      image: nginx:latest
      ports:
        - containerPort: 80
  restartPolicy: Always      
